# refresh_rate 配置文件的刷新速率，可以理解为每隔30s重新读取一次配置文件
refresh_rate: 30 seconds

# 输出管道 可以打印至控制台， 文件， 滚动文件 
appenders:
  # console 控制台输出的管道
  stdout:
    kind: console # kind 指定类型 console/file/rolling_file

  # requests 保存到文件的管道
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d} - {m}{n}"

  # roll 实现文件回滚的管道， 
  roll:
    kind: rolling_file
    path: "log/roll.log"
    append: true  # 追加模式
    encoder:
      kind: json  # pattern 和 json
    policy:
      kind: compound  # 即使用所有 policy
      # 触发器
      trigger:  # 当文件超过10mb 时触发 rotate
        kind: size
        limit: 10mb
      # 分割策略  
      roller:
        # kind: delete  # delete 回滚方式直接删除
        kind: fixed_window
        pattern: "logs/compressed-log-{}-.log"  # 注意, 需要至少包含 "{}" 用于插入索引值
        base: 0   # 压缩日志索引值起点
        count: 20  # 最大保存压缩文件数

# 全局log设置
root:
  level: info
  appenders:
    - stdout
    - roll
    # - requests

# 对特定工程进行配置，可选
# loggers:
#   app::backend::db:
#     level: info

  # app::requests:
  #   level: info
  #   appenders:
  #     - requests
  #   additive: false